[book]
authors = ["Karthik Inbasekar"]
language = "en"
multilingual = false
src = "src"
title = "Ingopedia"

[preprocessor.katex]
renderers = ["html"]

[output.katex]

[output.html]
curly-quotes = true
git-repository-url = "https://github.com/krakhit/test"
edit-url-template = " https://github.com/krakhit/test/edit/master/{path}"

[output.html.print]
page-break = false